apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewogICAgICAgICAgICAgICAgICAgICAgICJhdXRoIjogIlpuSnZZbUpsY25rNloyaHdYMFIyU21KeFduSkxSMEpZWTNBNFdtNHdUR3hOTlROSGFqbDVNMVJYV1RKTWJFWXpiZz09IgogICAgICAgICAgICAgICAgfQoJfSwKCSJjcmVkc1N0b3JlIjogImRlc2t0b3AiLAoJImN1cnJlbnRDb250ZXh0IjogImRlc2t0b3AtbGludXgiCn0K
type: kubernetes.io/dockerconfigjson
